apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
    - host: nginx.test.com
      http:
        paths:
          - backend:
              serviceName: nginx-http
              servicePort: 80
            path: /
