# 为容器设置启动时要执行的命令和参数
apiVersion: v1
kind: Pod
metadata:
  name: args-demo
  labels:
    name: args-demo
spec:
  containers:
    - name: args-demo
      image: debian
      command:
        - "/bin/echo"
      args: ["$(MESSAGE)"]
      env:
        - name: MESSAGE
          value: "hello k8s"
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
  restartPolicy: OnFailure
