# 限制cpu资源
# 虽然 stress 申请了2个cpu，但是限制在了1个
apiVersion: v1
kind: Pod
metadata:
  name: cpu-limit
  labels:
    name: cpu-limit
spec:
  containers:
    - name: cpu-limit
      image: registry.cn-beijing.aliyuncs.com/qingfeng666/stress
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      args:
        # 模拟程序本身申请2个cpu
        - -cpus
        - "2"
