# 为容器定义相互依赖的环境变量
# env 的顺序有依赖

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: busybox
      args:
        - printf UNCHANGED_REFERENCE=$UNCHANGED_REFERENCE'\n';printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n';printf ESCAPED_REFERENCE=$ESCAPED_REFERENCE'\n';sleep 3600;
        #UNCHANGED_REFERENCE=$(PROTOCOL)://192.168.1.1:80   PROTOCOL定义在引用之后，无法获取值
        #SERVICE_ADDRESS=https://192.168.1.1:80
        #ESCAPED_REFERENCE=$(PROTOCOL)://192.168.1.1:80  $$ 相当于转义成字符串
      command:
        - sh
        - -c
      env:
        - name: SERVICE_PORT
          value: "80"
        - name: SERVICE_IP
          value: "192.168.1.1"
        - name: UNCHANGED_REFERENCE
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: PROTOCOL
          value: "https"
        - name: SERVICE_ADDRESS
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: ESCAPED_REFERENCE
          value: "$$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
