apiVersion: v1
kind: Service
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    k8s-app: kube-etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2390
    protocol: TCP
    targetPort: 2390

---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    k8s-app: kube-etcd
subsets:
- addresses:
  - ip: 192.168.91.18
  - ip: 192.168.91.19
  - ip: 192.168.91.20
  ports:
  - name: http-metrics
    port: 2390
    protocol: TCP
